name: hello
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.0.0-171.0.dev <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    dio: ^4.0.6
    shared_preferences: ^2.0.17
    json_model: ^1.0.0
    json_serializable: ^5.0.0
    sp_util: ^2.0.3
    connectivity_plus: ^3.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
